steps:
  - ${{if eq(variables['Build.SourceBranch'], 'refs/heads/beta')}}:
    - powershell: |
        npx -p semantic-release@16.0.0-beta.22 semantic-release --branch beta

      displayName: 'Release beta'
      workingDirectory: 'build'
      env:
        NPM_TOKEN: $(NPM_TOKEN)
        GITHUB_TOKEN: $(GITHUB_TOKEN)
