steps:

  - template: install.yml

  # test project
  - script: yarn test:ci
    displayName: 'Run CI Tests'

  - powershell: |
      $flag = "$(Agent.OS)".toLower()
      npx codecov -t $env:TOKEN -F $flag
    displayName: 'Publish codecov'
    env:
      TOKEN: $(CODE_COV_JEST_JSONSHOT)

  # Publish CI test results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '*junit.xml'
      testRunTitle: 'CI Tests E2E $(Agent.OS)'
    displayName: 'Publish test results'
    condition: succeededOrFailed()
